### ISSUE TITLE
Offline mode

### ISSUE THREAD

**Issue by greenrd** [theScrabi/OCBookmarks#10]
It should be possible to add/edit bookmarks while offline, then sync later (maybe in the background, or maybe manually).

**Comment by dthrash** [comment]
Seconded. Anybody have solution for integration within chrome or firefox mobile?

**Comment by theScrabi** [comment]
@dthrash please open a separate thread for your question.

**Comment by theScrabi** [comment]
closing in favour of https://gitlab.com/derSchabi/OCBookmarks/issues/10
