### ISSUE TITLE
Error connection failed on a self signed server

### ISSUE THREAD

**Issue by JeromeSi** [theScrabi/OCBookmarks#16]
Hi,
when I try to connect to my nextcloud server (11.0.6) I've got this error.
I'm not a programmer but I've got this message in logcat : 
02-14 14:58:29.456 4336-4363/org.schabi.nxbookmarks W/System.err: org.schabi.ocbookmarks.REST.RequestException: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
[...]
02-14 14:58:29.459 4336-4363/org.schabi.nxbookmarks W/System.err: Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
[...]
02-14 14:58:29.460 4336-4363/org.schabi.nxbookmarks W/System.err: Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
[...]
02-14 14:58:29.462 4336-4363/org.schabi.nxbookmarks W/System.err: Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

Thanks for your work

![capture du 2018-02-14 15-06-07](https://user-images.githubusercontent.com/13288010/36208248-b7bd5376-1198-11e8-9e7e-c664fa2b72af.png)

**Comment by SomePoorBastard** [comment]
As a workaround, you can add that certificate as a trusted certificate in your phone. Get a copy of the public .crt, then under Settings -> Security -> Credential Storage, add the cert. Restart phone if necessary. Alternative is to use a Let's Encrypt cert and expose the Nextcloud instance to the internet for Let's Encrypt to verify the domain name your instance falls under. See Issue #4.

**Comment by theScrabi** [comment]
We should really fix this. I would like to do this my self, but I can't find time right now.

**Comment by SomePoorBastard** [comment]
I've forked this and am playing around with the code to see if I can present something workable. See https://github.com/SomePoorBastard/OCBookmarks.

**Comment by SomePoorBastard** [comment]
I have re-implemented the way secure errors are handled when the app sends a request to the server. See [Commit dab9959](https://github.com/SomePoorBastard/OCBookmarks/commit/dab9559d968c16d2f5fbf062fbb2dd721d5c52fb) for implementation details. However, through testing on an Android 8.0.0 device, I have determined that this error handling, which passes on responsibility to the user to add certificates in Android, is insufficient. I have added in a CA that I have created for a test instance of Nextcloud, and have determined that the error condition where a server's connection is untrusted still exists.

The Android Security Team has [changed](https://android-developers.googleblog.com/2016/07/changes-to-trusted-certificate.html) the way apps interact with Trusted CAs in Android. Apps used to trust 3rd-Party CAs that were added after the installation of Android by default. At API 24, this is no longer the case. Realizing that there was still a demand for this type of use case, they built an API for program logic to access the CA credentials on the device and determine whether they are trustworthy. The developer documentation [provided](https://developer.android.com/training/articles/security-ssl.html) gives a basic introduction to how to work around this.

**Comment by seth100** [comment]
@theScrabi hope you can find time to fix this.
My self-signed cert always changes so it is a problem for me to manually add it to my cert list.
Other NextCloud apps asks to accept cert and you can easily do it by pressing "Yes".
You can see those apps as reference.
Thanks

**Comment by theScrabi** [comment]
I see. Honestly this will be complicated time is still rare, and i simply have other projects that have a hight imprtance. I would be happy if i could get help with that.

**Comment by theScrabi** [comment]
closing in favour of https://gitlab.com/derSchabi/OCBookmarks/issues/16
