### ISSUE TITLE
Cannot Connect to a Self-Signed Server

### ISSUE THREAD

**Issue by ghost** [theScrabi/OCBookmarks#4]
What was done:
Connection attempt to URL https://127.0.0.1/nextcloud with correct username and password.
The server uses a self-signed certificate.

What was Expected:
Prompt that the server uses a self-signed/untrusted certificate, asking user whether trust it or not.

What Actually Happened:
Error messages without information about SSL or certificate.
Connection Failed. Check if
・You have internet access
・the URL is correct

What Worked:
Connecting to the server without SSL, which is much dangerous.

**Comment by theScrabi** [comment]
Whut
> 127.0.0.1 

You are running a nextcloud on your smartphone?

Plese use [cadroid](http://cadroid.bitfire.at/) to imoprt certificates to android.

**Comment by ghost** [comment]
> Plese use cadroid to imoprt certificates to android.

@theScrabi Thank you for the tip. It worked.
> You are running a nextcloud on your smartphone?

My mistake, it's the address that I use when I sit in front of the server.

I spent about 6 hours on learning how to setup a root CA and sign a certificate with it. It works like a charm with the certificate trusted. It also works on the [Notes](https://github.com/stefan-niedermann/nextcloud-notes) app.

**Comment by vlycop** [comment]
Hello
I have the same issue but with a self signed ca trusted by the device
 I added the ca.crt to my not rooted android and i nolonger have certificate issue with the browser or other nexcloud app, but i do with this one. I don't understand why

**Comment by Cloudbyte-Pony** [comment]
@vlycop 
In Android 7 (nougat) the applications no longer trust user installed CA's by default, don't know if that is your case. 

I fixed it by cloning the code, and changing the application network security configuration
to trust user CA's:
In the manifest I added:
`android:networkSecurityConfig="@xml/network_security_config"`
attribute in application. 

Then added the corresponding xml with:
`<network-security-config>
   <base-config>
        <trust-anchors>
            
            <certificates src="system" />
            
            <certificates src="user" />
        </trust-anchors>
    </base-config>
</network-security-config>`

Recompiled and voila!, it now works with user installed CAs in Nougat.
I think this *may* pose a security risk in case somehow a rogue CA was installed in your phone,
but for me I'm willing to deal with that. Now if I could add proxy support to this....

**Comment by vlycop** [comment]
Yay for you @Cloudbyte-Pony ! Well, i never compiled anything for android, but i might have to.
Oh, and to me there is no security risk. I get spamed by a " you device internet trafic may be monitored by a third party" popup since i have added my cert, so i think if someone add a cert without you knowing.... You will know quick enought :-)

**Comment by theScrabi** [comment]
@CloudByte-Pony
If you like you could add dialog window that pops up once a self signed cert appears, and send it as pull request.

**Comment by AndreasAusD** [comment]
i tried to use cadroid, but it would not install the certificate because of a CA Flag being set to FALSE.
After correcting that and generating new certificates it is working for me.
Some additional catch for SSL-related errors in the TestLoginTask would have helped :-)

**Comment by filipesaraiva** [comment]
I am having the same problem. Maybe is it the same problem with OCReader?

**Comment by cmouzaoui** [comment]
I'm getting the same issue: installing my self-signed server's certificate as a user certificate is not working, and CADroid gives the error "The certificate chain doesn't contain a valid certificate for the host name in the URL. Use the correct host name or change the corresponding certificate's subject."
Could you indeed send a pull request @Cloudbyte-Pony ?

**Comment by mat-ale** [comment]
Same issue.
Any hope to implement something like other NextCloud apps do (e.g. https://github.com/stefan-niedermann/nextcloud-notes/issues/125#issuecomment-340094056) to import Self-Signed certs?
Thanks

**Comment by theScrabi** [comment]
Closing in favour of https://gitlab.com/derSchabi/OCBookmarks/issues/4
