### ISSUE TITLE
Widget + available tags

### ISSUE THREAD

**Issue by Seferi** [theScrabi/OCBookmarks#7]
Is it possible to have a widget for easy access to the bookmarks under available tags?
 Also when adding a bookmark, to be able to choose from already available tags?

**Comment by theScrabi** [comment]
Yes but I barely have time to implement it right now.

**Comment by Seferi** [comment]
I understand mate. I'd appreciate if you could add it to your to do list.. Otherwise great app, have been using it daily, thanks for all the work you have done!

**Comment by theScrabi** [comment]
Closing in favour of https://gitlab.com/derSchabi/OCBookmarks/issues/7
