### ISSUE TITLE
Can't connect to the server

### ISSUE THREAD

**Issue by jpggithub** [theScrabi/OCBookmarks#8]
If I use "https://my.server.com/", it becomes "https://my.server.co" and does.not connect.

If put the adress without the last /,the app can't connect.

If I use the same adress by copy/paste in my browser, it works.

I use version 1.1 on fdroid.org.

**Comment by theScrabi** [comment]
Strange. Confirmed tho. That is a stupid error -.-

**Comment by jpggithub** [comment]
When I don't put the last /, it said

Connection failed. Check if 
- You have Internet access
- the URL is correct

**Comment by theScrabi** [comment]
Yes of course:
https://github.com/theScrabi/OCBookmarks/blob/master/app/src/main/java/org/schabi/ocbookmarks/LoginAcitivty.java#86

-2

Who gave me the right to program?

**Comment by jpggithub** [comment]
Sorry, english is not my native langage and I'm not a developer.
Is it humor? :-/

**Comment by theScrabi** [comment]
It is :)

**Comment by jpggithub** [comment]
Ok, you can continue tu program ;-)

**Comment by theScrabi** [comment]
Closing in favour of https://gitlab.com/derSchabi/OCBookmarks/issues/8

**Comment by jpggithub** [comment]
I think the given link below is bad because the issue #8 can't refer to itself ;-)

**Comment by theScrabi** [comment]
it points to gitlab not to github.
