### ISSUE TITLE
Autocomplete existing tags

### ISSUE THREAD

**Issue by juliusknorr** [theScrabi/OCBookmarks#9]
When adding a new bookmark existing tags should be displayed when you start to type something.

**Comment by aslmx** [comment]
That would really help to sort bookmarks into the right "todo workflow"

Please consider it!

**Comment by theScrabi** [comment]
I'd like that. Help is always welcome ;)

**Comment by aslmx** [comment]
I can offer help with testing or translation, but apparently i'm not a developer

**Comment by theScrabi** [comment]
closing in favour of https://gitlab.com/derSchabi/OCBookmarks/issues/9
